# Generated by Django 4.2.1 on 2023-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_author_user_id_issues_author_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Faible"), ("MED", "Moyen"), ("HIGH", "Haute")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="tag",
            field=models.CharField(max_length=255),
        ),
    ]
