# Generated by Django 4.2.1 on 2023-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_issues_priority_alter_issues_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="author_user_id",
            new_name="author_user",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="id",
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="projects",
            name="type",
            field=models.CharField(
                choices=[
                    ("Feature", "Feature"),
                    ("Bug", "Bug"),
                    ("Enhancement", "Enhancement"),
                    ("Task", "Task"),
                    ("Other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
