# Generated by Django 4.2.1 on 2023-06-30 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_author_user_id_comments_author_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="issue_id",
            new_name="issue",
        ),
    ]
