# Generated by Django 4.2.3 on 2023-07-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_issue_id_comments_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='project_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.projects'),
            preserve_default=False,
        ),
    ]
